language: android

sudo: false

jdk:
  - oraclejdk7

android:
  components:
    - platform-tools
    - tools     # see https://github.com/travis-ci/travis-ci/issues/5036
    - android-23
    - build-tools-23.0.3
    - extra-google-m2repository
    - extra-android-m2repository

script: GRADLE_OPTS="-Xmx768m -Xms256m -Xss1m" ./gradlew build check --stacktrace
