language: android

sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools     # see https://github.com/travis-ci/travis-ci/issues/5036
    - android-24
    - build-tools-24.0.0
    - extra-google-m2repository
    - extra-android-m2repository

script: GRADLE_OPTS="-Xmx768m -Xms256m -Xss1m" ./gradlew build check --stacktrace
